[package]
name = "devops-automerge"
version = "0.1.0"
edition = "2024"

[dependencies]
async-signal = "0.2.14"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
bytes = "1.11.1"
cloneable_errors = "2.3.0"
ctutils = "0.4.2"
futures-lite = "2.6.1"
graphql_client = "0.16.0"
hmac = "0.13.0"
octocrab = "0.51.0"
reqwest = "0.13.3"
serde = { version = "1.0.228", features = ["derive", "rc"] }
sha2 = "0.11.0"
tokio = { version = "1.52.3", features = ["io-util", "net", "rt-multi-thread"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
todo = "warn"

[profile.release]
strip = true
lto = "thin"
