[package]
name = "devops-automerge"
version = "0.1.0"
edition = "2024"
build = "src/build_script.rs"

[dependencies]
async-signal = "0.2.14"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
bytes = "1.11.1"
cloneable_errors = "2.3.0"
ctutils = "0.4.2"
futures = { version = "0.3.32", default-features = false, features = ["async-await", "std"] }
glob = "0.3.3"
graphql_client = "0.16.0"
hmac = "0.13.0"
jsonwebtoken = { version = "11.0.0" }
octocrab = { version = "0.51.0", default-features = false, features = ["default-client", "follow-redirect", "jwt-rust-crypto", "retry", "rustls", "rustls-webpki-tokio", "timeout", "tracing"] }
reqwest = "0.13.3"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.150"
sha2 = "0.11.0"
tokio = { version = "1.52.3", features = ["io-util", "net", "rt-multi-thread"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
yaml_serde = "0.10.4"

[build-dependencies]
cloneable_errors = "2.3.0"
reqwest = { version = "0.13.3", features = ["blocking"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
todo = "warn"

[package.metadata.bacon]
default_job = "clippy"

[package.metadata.bacon.jobs.clippy]
watch = ["queries"]
command = ["cargo", "clippy"]
need_stdout = false

[profile.release]
strip = true
lto = "thin"
