[listen]
tcp = "[::]:8080"
unix = "/tmp/automerge.sock"
unix_mode = 0o666

[app]
webhook_secret = "webhook secret that should be secret"
app_id = 2137
private_key = """
-----BEGIN RSA PRIVATE KEY-----
rsa key contents would be here if this
was an actual private key (which it is not)
-----END RSA PRIVATE KEY-----
"""


[[rules]]
# rule name, for debugging
name = "repo 1"
# repos to apply this rule to
repositories = ["Solvro/lib-web-solvro-config"]
# available methods:
# instant_*: merge, squash, rebase
# auto_*: merge, squash, rebase
# add_to_merge_queue
merge_method = "auto_squash"
# allowed base branches
branches = ["main"]
# allowed file paths
allowed_paths = ["package-lock.json", "package.json"]
# max commits allowed for an automerged pr
max_commits = 4
# max modfied files allowed
max_files = 3
# max additions + deletions
max_changed_lines = 67

[rules.dependabot]
dependency_names = ["@solvro/config"]
dependency_groups = ["typescript-eslint"]
dependency_types = ["direct:production"]
update_types = ["version-update:semver-patch", "version-update:semver-minor"]
